name: "Deploy Angular Website to AWS through CloudFront distribution using S3 as origin GitHub Actions"

on:
  push:
    branches: ["master", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Build and Deploy using Angular GitHub Actions
        uses: mayurrawte/github-angular-actions@latest
        # with:
        #   github_access_token: ${{ secrets.ACCESS_TOKEN }}
        #   build_configuration: production
        # #  base_href: "" 
        #   deploy_branch: develop 
        #   angular_dist_build_folder: dist/
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Copy to S3    
        env:
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: aws s3 sync . s3://${S3_BUCKET}
      - name: Invalidating CloudFront Cache
        env: 
          CLOUDFRONT_DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
        run: aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths "/*"